### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iswarmondal**
Added the question of  `What is e-bureau` and the answer for more clarity.

### CODE REVIEW

**Comment by madihamallick** [comment]
@iswarmondal Good work

**Comment by madihamallick** [comment]
@iswarmondal Please give your participant id of SWOC

**Comment by iswarmondal** [comment]
I haven't participated in SWOC. I think the new application date is up. Is there anything we can do?

**Comment by madihamallick** [comment]
Okay. No I don't think they are accepting participants as the program is about to end now.

**Pull request merged**
