### PR TITLE
signup page with email verification

### PR DESCRIPTION
**Pull request by anugoyal998**
Created a signup page with **Email verification**. Passwords are hashed before storing them to the database. I have kept the UI same as the `General Diary` page has. For sending OTP to email I used `nodemailer`.
Before reviewing edit the environment variables. Edit `NODEMAILER_SENDER_ID` with the Gmail id from which you want to send OTP mail and `NODEMAILER_SENDER_ID_PASSWORD` with the password of your Gmail account.
Signup Page
Verification Page

### CODE REVIEW

**Comment by madihamallick** [comment]
@anugoyal998 Please resolve the conflicts

**Comment by anugoyal998** [comment]
> @anugoyal998 Please resolve the conflicts

Can you brief the error you are getting as on my system it's working fine.
I think you have to change tha google account settings from which you are sending emails.
Go to your Google account > search for less secure apps> enable it

**Comment by madihamallick** [comment]
> > @anugoyal998 Please resolve the conflicts
> 
> Can you brief the error you are getting as on my system it's working fine. I think you have to change the google account settings from which you are sending emails. Go to your Google account > search for less secure apps> enable it

No I am not talking about that. The code which you cloned is not uptodate just type in your terminal,

`git pull origin main`

Then add your code. Then make a PR.

**Comment by anugoyal998** [comment]
> > > @anugoyal998 Please resolve the conflicts
> > 
> > Can you brief the error you are getting as on my system it's working fine. I think you have to change the google account settings from which you are sending emails. Go to your Google account > search for less secure apps> enable it
> 
> No I am not talking about that. The code which you cloned is not uptodate just type in your terminal,
> 
> `git pull origin main`
> 
> Then add your code. Then make a PR. 

Ok

**Pull request closed without merging**
