### PR TITLE
New Footer ADDED

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
Hi @geekymeeky  I have successfully resolve the issue number #53  Hope you will love this resolve.
Here is the photo
footer

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
hi @geekymeeky  I successfully resolved the issue number #53

**Comment by madihamallick** [comment]
Good Work! 🐱‍🏍 @Abh1shekSingh

**Comment by Abh1shekSingh** [comment]
Thanks You

**Comment by Abh1shekSingh** [comment]
On it. @geekymeeky/e-bureau
***@***.***>

**Pull request merged**
