### PR TITLE
Added Signup Page with Email and Mobile verification

### PR DESCRIPTION
**Pull request by anugoyal998**
Create a signup page with OTP verification both email and mobile. Passwords are hashed before storing them to the database. I have kept the UI same as the `General Diary` page has. For sending OTPs to mobile and email I used `Twillio` and `Nodemailer`.
Before reviewing edit the environment variables. Setup your `Twillio` account and edit `TWILLIO_NUMBER`, `TWILIO_ACCOUNT_SID`, `TWILIO_AUTH_TOKEN` in .env with your credentials. Also, edit `NODEMAILER_SENDER_ID` with the Gmail id from which you want to send OTP mail and `NODEMAILER_SENDER_ID_PASSWORD` with the password of your Gmail account. The Gmail password in .env is my previous Gmail password I have changed the password of my Gmail account.
Signup Page
Verification Page

### CODE REVIEW

**Comment by madihamallick** [comment]
There is an error. @anugoyal998 please check.
Capture

**Comment by madihamallick** [comment]
> Create a signup page with OTP verification both email and mobile. Passwords are hashed before storing them to the database. I have kept the UI same as the `General Diary` page has. For sending OTPs to mobile and email I used `Twillio` and `Nodemailer`. Before reviewing edit the environment variables. Setup your `Twillio` account and edit `TWILLIO_NUMBER`, `TWILIO_ACCOUNT_SID`, `TWILIO_AUTH_TOKEN` in .env with your credentials. Also, edit `NODEMAILER_SENDER_ID` with the Gmail id from which you want to send OTP mail and `NODEMAILER_SENDER_ID_PASSWORD` with the password of your Gmail account. The Gmail password in .env is my previous Gmail password I have changed the password of my Gmail account. Signup Page Verification Page

Okay

**Comment by madihamallick** [comment]
@anugoyal998 use Firebase to verify user details since Twilio is a paid service kindly use firebase to verify user details.

**Comment by anugoyal998** [comment]
> @anugoyal998 use Firebase to verify user details since Twilio is a paid service kindly use firebase to verify user details. 

Ok

**Comment by anugoyal998** [comment]
> > @anugoyal998 use Firebase to verify user details since Twilio is a paid service kindly use firebase to verify user details.
> 
> Ok

@madihamallick can I skip the mobile verification part as I'm not familiar with firebase

**Comment by madihamallick** [comment]
> > > @anugoyal998 use Firebase to verify user details since Twilio is a paid service kindly use firebase to verify user details.
> > 
> > 
> > Ok
> 
> @madihamallick can I skip the mobile verification part as I'm not familiar with firebase

Yes sure!

**Comment by anugoyal998** [comment]
> > > > @anugoyal998 use Firebase to verify user details since Twilio is a paid service kindly use firebase to verify user details.
> > > 
> > > 
> > > Ok
> > 
> > @madihamallick can I skip the mobile verification part as I'm not familiar with firebase
> 
> Yes sure!

Ok

**Pull request closed without merging**
