### PR TITLE
#added the Home page page 

### PR DESCRIPTION
**Pull request by shefali12-ab**
fixed  tailwind css issue.
now that the signup and login buttons need to make clickable and perform their functioning.
localhost-3000-LandingPage

### CODE REVIEW

**Comment by madihamallick** [comment]
Great work @shefali12-ab ✨  just try to make the lower part of dark theme too so that it matches the upper portion.

**Comment by shefali12-ab** [comment]
@madihamallick thank you :)),
 yeah, I will add these changes.

**Comment by madihamallick** [comment]
> @madihamallick thank you :)), yeah, I will add these changes.

@shefali12-ab update?

**Comment by shefali12-ab** [comment]
@madihamallick yeah i have made the changes .

**Comment by shefali12-ab** [comment]
localhost-3000-LandingPage (1)
@madihamallick is this okay??

**Comment by madihamallick** [comment]
Looks Good! 😍

**Pull request merged**
